# Generated by Django 2.1.7 on 2019-10-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashes',
            fields=[
                ('hashValue', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
    ]
